### PR TITLE
update readme

### PR DESCRIPTION
**Pull request by ganapathi12**
hacktoberfest

### CODE REVIEW

**Comment by HimanSC** [comment]
Hey can I contribute for hacktoberfest?

**Comment by HariAcidReign** [comment]
yo does this trick of making PRs on ur own repo actually work? is it valid? 😂😂

**Comment by balajidass07** [comment]
Yes of course @SmashedTrash

**Comment by balajidass07** [comment]
Ya bro @HariAcidReign its vaild

**Comment by ganapathi12** [comment]
> yo does this trick of making PRs on ur own repo actually work? is it valid? 😂😂

its working da! but not on our own repo's

**Pull request merged**
